knp_paginator:
    page_range: 5                      # Nombre de pages affichées dans la barre de pagination
    default_options:
        page_name: page                # Nom du paramètre de la page dans l'URL
        sort_field_name: sort          # Nom du paramètre pour trier les résultats
        sort_direction_name: direction # Nom du paramètre pour la direction du tri
        distinct: true                 # Empêche les doublons dans la pagination
